### ISSUE TITLE
No explicit license for the code

### ISSUE THREAD

**Issue by jeantil** [globocom/docker-swift-keystone#1]
Hi, 

There is no License in the repository which makes the code here proprietary by default.

I would very much like to lift and adapt `setup-keystone.sh` to provide the `bouncestorage/docker-swift` docker image with keystone auth capability. 

Would you accept to add a GPL v2 compatible LICENSE for your code or at least for `setup-keystone.sh`? 

Thanks in advance.

**Comment by jeantil** [comment]
Hi @fabio-gomes, 

I apologise for the direct ping. I wanted to be sure you saw the above issue.

Thanks
jean

**Comment by fabio-gomes** [comment]
Hi @jeantil , 

Adding the MIT License would help you?

(https://choosealicense.com/licenses/mit/) 

Thanks,
Fábio

**Comment by jeantil** [comment]
Definitely !

Le mar. 4 sept. 2018 à 18:39, fabio-gomes <notifications@github.com> a
écrit :

**Comment by fabio-gomes** [comment]
Hi @jeantil ,

I've just added MIT License to project.

Thanks,
Fábio.

**Comment by jeantil** [comment]
Awesome thank you!

Le mar. 4 sept. 2018 à 19:10, fabio-gomes <notifications@github.com> a
écrit :
